"""Starting browsers as GoLogin (Orbita) profiles.

A GoLogin profile carries its own fingerprint, proxy, cookies and local
storage, which is what replaces UC mode here: the anti-bot layer sees a browser
identity that GoLogin maintains, not a patched chromedriver on this machine.

GoLogin starts Orbita itself and hands back a DevTools debugger address; we
attach Selenium to that, then wrap the driver in SBShim so the existing steps
keep working unchanged.

Ported from the standalone gologin_nav.py, including its chromedriver pinning:
Orbita reports versions like "132.1.2.73", which is not a real chromedriver
release, so only the major version is worth matching -- and it has to be
widened to a real four-part version first, because webdriver-manager handed a
bare major quietly installs a different one that then refuses to attach.
"""

import os

# The GoLogin SDK wires up a Sentry client in GoLogin.__init__ and ships
# exceptions to their server unless this is set before the import.
os.environ.setdefault("DISABLE_TELEMETRY", "true")

import random
import shutil
import threading
from contextlib import contextmanager

import requests
from gologin import GoLogin
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

from .config import RunConfig
from .errors import AwBotError
from .logs import LOG
from .sb_shim import SBShim
from . import environment, real_input, stealth, turnstile

CFT_LATEST_RELEASE = "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_{major}"


class GoLoginError(AwBotError):
    """GoLogin could not give us a usable browser."""


# ---------------------------------------------------------------------------
# profiles
# ---------------------------------------------------------------------------


def fetch_profiles(token: str) -> list[dict]:
    """Every profile on the account."""
    gl = GoLogin({"token": token, "profile_id": None})
    payload = gl.profiles()
    # /browser/v2 answers with {"profiles": [...]}; tolerate a bare list too.
    if isinstance(payload, dict):
        return payload.get("profiles", []) or []
    return payload or []


def list_profiles(token: str) -> int:
    """Print the account's profiles. Returns a process exit code."""
    profiles = fetch_profiles(token)
    if not profiles:
        print("No profiles on this account (or the token lacks access to them).")
        return 1

    print(f"{len(profiles)} profile(s):\n")
    for profile in profiles:
        proxy = profile.get("proxy") or {}
        where = proxy.get("host") or proxy.get("mode") or "no proxy"
        print(f"  {profile.get('id')}  {profile.get('name', '<unnamed>')}")
        print(f"      os={profile.get('os', '?')}  proxy={where}")
    print("\nPut the ID you want in .env as GOLOGIN_PROFILE_ID.")
    return 0


# Profiles this project generates are named `aw-<worker>-<random>`. Nothing
# else on the account should carry that prefix, which is what makes it safe to
# tidy them up without touching a profile somebody made by hand.
DISPOSABLE_PREFIX = "aw-"


def _is_disposable(profile: dict) -> bool:
    return str(profile.get("name") or "").startswith(DISPOSABLE_PREFIX)


def count_profiles(token: str) -> tuple[int, int]:
    """(profiles held, how many of those are leftovers from earlier runs).

    Best-effort: a failed lookup answers (0, 0) rather than stopping a run
    over a warning it could not compose.
    """
    try:
        profiles = fetch_profiles(token)
    except Exception as exc:
        LOG.debug("Could not count profiles: %s", exc)
        return 0, 0
    return len(profiles), sum(1 for p in profiles if _is_disposable(p))


def cleanup_disposable_profiles(token: str, dry_run: bool = False) -> int:
    """Delete the `aw-*` profiles left behind by earlier runs.

    A GoLogin account has a hard cap on how many profiles it may hold, and a
    run that is interrupted -- or one using --keep-open before that stopped
    leaking -- leaves one behind per lead. Once the cap is reached every
    subsequent lead fails at the first step with a 403 and never opens a
    browser at all, which reads as the site refusing us rather than as an
    account that is simply full.

    Only touches names beginning `aw-`, so a profile made by hand is never at
    risk. Returns how many were removed.
    """
    try:
        profiles = fetch_profiles(token)
    except Exception as exc:
        raise GoLoginError(f"Could not list profiles: {exc}") from exc

    leftovers = [p for p in profiles if _is_disposable(p)]
    kept = len(profiles) - len(leftovers)

    if not leftovers:
        LOG.info(
            "No leftover profiles to remove (%d profile(s) on the account, "
            "none of them generated by this project).", len(profiles),
        )
        return 0

    LOG.info(
        "%d leftover profile(s) to remove; %d other profile(s) will be left "
        "alone.", len(leftovers), kept,
    )
    if dry_run:
        for profile in leftovers:
            LOG.info("  would delete %s  %s", profile.get("id"), profile.get("name"))
        return 0

    removed = 0
    for profile in leftovers:
        profile_id = profile.get("id")
        if not profile_id:
            continue
        if delete_profile(token, profile_id):
            removed += 1
    LOG.info("Removed %d leftover profile(s).", removed)
    return removed


class ProfilePool:
    """Hands out profiles so two workers never start the same one at once.

    GoLogin will not run one profile in two browsers, so with several workers
    the pool has to have at least that many profiles in it. A worker that asks
    while every profile is busy waits for one to come back.
    """

    def __init__(self, token: str, profile_ids: list[str]) -> None:
        if not profile_ids:
            raise GoLoginError(
                "No GoLogin profiles to run. Set GOLOGIN_PROFILE_ID in .env, pass "
                "--gologin-profile, or use --random-profile to draw from the account."
            )
        self.token = token
        self.all_ids = list(profile_ids)
        self._free = list(profile_ids)
        self._condition = threading.Condition()

    def __len__(self) -> int:
        return len(self.all_ids)

    @contextmanager
    def lease(self, release: bool = True):
        """Borrow a profile id. `release=False` retires it for the rest of the
        run -- that is what --keep-open needs, since the browser is still up
        and GoLogin would refuse to start the same profile a second time.
        """
        with self._condition:
            while not self._free:
                LOG.info("All %d GoLogin profile(s) busy; waiting for one", len(self.all_ids))
                self._condition.wait()
            # Random rather than round-robin: consecutive leads then come from
            # different identities even when the pool is small.
            profile_id = self._free.pop(random.randrange(len(self._free)))
        try:
            yield profile_id
        finally:
            if release:
                with self._condition:
                    self._free.append(profile_id)
                    self._condition.notify()


def resolve_profile_ids(cfg: RunConfig) -> list[str]:
    """Which profiles this run may use."""
    gl_cfg = cfg.gologin
    if gl_cfg.random_profile or not gl_cfg.profile_ids:
        ids = [p["id"] for p in fetch_profiles(gl_cfg.token) if p.get("id")]
        if not ids:
            raise GoLoginError(
                "This account has no profiles (or the token cannot see them). "
                "Create one at app.gologin.com first."
            )
        LOG.info("Drawing from all %d profile(s) on the account", len(ids))
        return ids
    return list(gl_cfg.profile_ids)


# ---------------------------------------------------------------------------
# disposable profiles
# ---------------------------------------------------------------------------


def create_disposable_profile(cfg: RunConfig, worker_id: int = 1) -> tuple[str, str]:
    """Build a throwaway GoLogin profile with its own fingerprint and proxy.

    Returns (profile_id, description).

    The fingerprint comes from GoLogin's own generator rather than anything
    assembled here, and that is deliberate: it returns a *coherent* identity
    where the OS, user agent, screen, GPU, font list and timezone were chosen
    to agree with each other. Hand-picking a few of those values is how you
    end up with a browser claiming one machine while the rest of it says
    another, which is more visible than an ordinary fingerprint, not less.
    """
    gl_cfg = cfg.gologin
    gl = GoLogin({"token": gl_cfg.token, "profile_id": None})

    os_choice = _pick_os(gl_cfg.profile_os)
    name = f"aw-{worker_id}-{random.randint(100000, 999999)}"

    try:
        created = gl.createProfileRandomFingerprint({"os": os_choice, "name": name})
    except Exception as exc:
        raise GoLoginError(f"Could not create a GoLogin profile: {exc}") from exc

    profile_id = _created_id(created)
    if not profile_id:
        raise GoLoginError(f"GoLogin did not return a profile id (got {created!r})")

    LOG.info("[w%d] Created profile %s (%s, os=%s)", worker_id, profile_id, name, os_choice)

    _freshen_user_agent(gl, profile_id, worker_id)

    try:
        gl.addGologinProxyToProfile(
            profile_id, gl_cfg.proxy_country, gl_cfg.proxy_type or ""
        )
        LOG.info(
            "[w%d] Attached a %s %s proxy",
            worker_id, gl_cfg.proxy_country, gl_cfg.proxy_type or "auto-selected",
        )
    except Exception as exc:
        # A profile with no proxy would go out on this machine's own IP --
        # which the enrollment host refuses outright, and which would also
        # put the operator's home connection in front of the site. Delete it
        # and fail rather than quietly running without the proxy.
        delete_profile(gl_cfg.token, profile_id, worker_id)
        raise GoLoginError(
            f"Could not attach a proxy to the new profile ({exc}). "
            f"Check the account's {gl_cfg.proxy_type or 'proxy'} traffic balance."
        ) from exc

    # After the proxy, because what it fixes depends on the exit being known.
    _match_profile_to_proxy(gl, profile_id, worker_id)

    return profile_id, f"{name} ({os_choice})"


# Roughly the share of US desktop Chrome each platform actually has. An even
# split between Windows and macOS is not a neutral choice -- it is a choice
# that makes every other profile a Mac, which is about three times as many as
# the real population has. The point of a generated fingerprint is to be
# unremarkable, and "unremarkable" is a distribution, not a coin flip.
_OS_WEIGHTS = {"win": 78, "mac": 18, "lin": 4}


def _pick_os(allowed) -> str:
    """One OS from `allowed`, drawn the way the real population is shaped."""
    options = tuple(allowed or ("win",))
    weights = [_OS_WEIGHTS.get(name, 1) for name in options]
    return random.choices(options, weights=weights, k=1)[0]


def _freshen_user_agent(gl, profile_id: str, worker_id: int) -> None:
    """Move the profile's user agent up to the browser version it will run as.

    GoLogin's generator picks a user agent from its own pool, and that pool
    lags the Orbita build the profile is actually launched with. The result is
    a browser whose UA claims one Chrome while everything measured underneath
    it -- the client-hint brand list, the JS engine's behaviour, the TLS and
    HTTP/2 fingerprints -- belongs to another. That disagreement is worth more
    to anything checking than the UA string itself, because a plain UA is
    shared with millions of people and a contradiction is shared with almost
    nobody.

    Best-effort: a profile with a slightly old UA is still usable, so a
    failure here is logged and the lead goes ahead.
    """
    try:
        gl.updateUserAgentToLatestBrowser([profile_id])
        LOG.info("[w%d] User agent matched to the current browser build", worker_id)
    except Exception as exc:
        LOG.warning(
            "[w%d] Could not update the profile's user agent (%s). The profile "
            "still works; its UA may name an older Chrome than Orbita runs.",
            worker_id, exc,
        )


def _match_profile_to_proxy(gl, profile_id: str, worker_id: int) -> None:
    """Stop the profile contradicting the proxy it goes out through.

    Reads the profile and only changes what is actually wrong, rather than
    writing a set of values over the top -- the generated fingerprint is
    coherent and worth leaving alone.

    The one that matters is WebRTC. In `real` mode the browser answers STUN
    with the machine's true address, so a page can read the home IP straight
    past the proxy: the site sees a residential exit in California and a
    WebRTC candidate from wherever this computer is. Nothing else in the
    fingerprint matters if that is on.
    """
    try:
        gl.setProfileId(profile_id)
        profile = gl.getProfile(profile_id) or {}
    except Exception as exc:
        LOG.debug("[w%d] Could not read the new profile back: %s", worker_id, exc)
        return

    changes: dict = {}

    webrtc = dict(profile.get("webRTC") or {})
    if webrtc.get("mode") == "real" or webrtc.get("fillBasedOnIp") is False:
        webrtc["mode"] = "alerted"        # GoLogin's name for "masked"
        webrtc["fillBasedOnIp"] = True    # follow the proxy exit, not this machine
        changes["webRTC"] = webrtc

    # The timezone should come from the exit IP too. A browser in
    # America/Los_Angeles behind a New York exit is the same kind of
    # contradiction, and GoLogin will derive it if asked.
    timezone = dict(profile.get("timezone") or {})
    if timezone.get("fillBasedOnIp") is False:
        timezone["fillBasedOnIp"] = True
        changes["timezone"] = timezone

    if not changes:
        LOG.debug("[w%d] Profile already agrees with its proxy", worker_id)
        return

    try:
        gl.update({"id": profile_id, **changes})
        LOG.info(
            "[w%d] Pointed %s at the proxy exit", worker_id, ", ".join(changes)
        )
    except Exception as exc:
        LOG.warning(
            "[w%d] Could not align the profile with its proxy (%s): %s",
            worker_id, ", ".join(changes), exc,
        )


def _created_id(created) -> str:
    """The profile id out of whatever shape the API answered with."""
    if isinstance(created, str):
        return created
    if isinstance(created, dict):
        for key in ("id", "_id", "profileId", "browserId"):
            value = created.get(key)
            if value:
                return str(value)
    return ""


def delete_profile(token: str, profile_id: str, worker_id: int = 1) -> bool:
    """Remove a disposable profile. Never raises: it is cleanup.

    Returns whether it went, so a bulk tidy-up can report an honest count.
    """
    try:
        GoLogin({"token": token, "profile_id": profile_id}).delete(profile_id)
        LOG.info("[w%d] Deleted profile %s", worker_id, profile_id)
        return True
    except Exception as exc:
        # Worth saying: these accumulate against the account's profile limit,
        # and a run that leaks them will eventually fail to create more.
        LOG.warning(
            "[w%d] Could not delete profile %s: %s -- remove it at app.gologin.com",
            worker_id, profile_id, exc,
        )
        return False


# ---------------------------------------------------------------------------
# chromedriver
# ---------------------------------------------------------------------------

_driver_cache: dict[str, str | None] = {}
_driver_lock = threading.Lock()


def _latest_driver_for_major(major: str) -> str | None:
    """The newest chromedriver on a given Chrome major, e.g. 132.0.6834.159."""
    try:
        response = requests.get(CFT_LATEST_RELEASE.format(major=major), timeout=20)
        response.raise_for_status()
    except requests.RequestException as exc:
        LOG.warning("Could not look up a chromedriver for Chrome %s: %s", major, exc)
        return None

    version = response.text.strip()
    # A missing major returns an error page, not a version string.
    if not version.startswith(f"{major}.") or len(version.split(".")) != 4:
        return None
    return version


def resolve_chromedriver(chromium_version: str, explicit: str = "") -> str | None:
    """Path to a chromedriver matching Orbita, or None to let Selenium Manager decide."""
    if explicit:
        return explicit

    major = (chromium_version or "").split(".")[0]
    if not major.isdigit():
        LOG.warning("Could not read Orbita's version; falling back to Selenium Manager")
        return None

    # One lookup per Chrome major per process, not one per lead.
    with _driver_lock:
        if major in _driver_cache:
            return _driver_cache[major]

        path = None
        exact = _latest_driver_for_major(major)
        if exact is None:
            LOG.warning("No chromedriver published for Chrome %s; trying Selenium Manager", major)
        else:
            try:
                from webdriver_manager.chrome import ChromeDriverManager

                path = ChromeDriverManager(driver_version=exact).install()
            except Exception as exc:  # any failure here just means "try Selenium Manager"
                LOG.warning("webdriver-manager could not fetch chromedriver %s: %s", exact, exc)

        _driver_cache[major] = path
        return path


# ---------------------------------------------------------------------------
# sessions
# ---------------------------------------------------------------------------


def attach_driver(debugger_address: str, driver_path: str | None, cfg: RunConfig):
    """Attach Selenium to the Orbita instance GoLogin already started."""
    options = Options()
    options.add_experimental_option("debuggerAddress", debugger_address)

    # "eager" returns the navigation at DOMContentLoaded instead of waiting on
    # every last subresource. Measured on these profiles, the start page is
    # interactive and fully usable at ~38s but keeps trickling in well past
    # that -- the residential proxy is simply slow, and the default "normal"
    # strategy turns a working page load into a timeout.
    options.page_load_strategy = "eager"

    # Chrome's console and network logs -- off unless asked for.
    #
    # These are not free. To serve them ChromeDriver turns on the CDP Runtime
    # and Network domains for the whole session, and a page can tell. The
    # standard check costs a page nothing: hand `console.log` an object with a
    # getter on `.stack`, and the getter fires only when something is
    # listening on Runtime. Cloudflare is known to probe for exactly that, and
    # it is one of the few signals that separates a browser being *driven*
    # from the same browser being used, whatever its fingerprint says.
    #
    # Which matters here, because the profile passes by hand and gets a
    # "Verify you are human" checkbox under automation. Worth being sure this
    # is not the reason before blaming the proxy.
    #
    # The irony is that these logs were turned on to diagnose "(600)" -- so
    # the diagnostic may have been feeding the problem it was measuring. Left
    # available behind --capture-logs for when that trade is worth making.
    if getattr(cfg, "capture_browser_logs", False):
        LOG.warning(
            "Browser/network logging is on. It enables the CDP Runtime and "
            "Network domains, which anti-bot scoring can detect -- use it to "
            "diagnose, not for production runs."
        )
        options.set_capability(
            "goog:loggingPrefs", {"browser": "ALL", "performance": "ALL"}
        )

    if driver_path:
        driver = webdriver.Chrome(service=Service(driver_path), options=options)
    else:
        driver = webdriver.Chrome(options=options)

    driver.set_page_load_timeout(cfg.page_timeout)
    return driver


@contextmanager
def gologin_session(cfg: RunConfig, profile_id: str, worker_id: int = 1):
    """Start `profile_id`, yield an sb-shaped handle, then stop and sync it back."""
    gl_cfg = cfg.gologin
    extra = list(gl_cfg.extra_args)
    if gl_cfg.disable_extensions and not any(
        a.startswith("--disable-extensions") for a in extra
    ):
        # See GoLoginConfig.disable_extensions: the bundled ad blocker blocks
        # Akamai's bot sensor, which is what gets these profiles refused.
        extra.append("--disable-extensions")

    if getattr(cfg, "allow_third_party_storage", False):
        # Turnstile runs three frames deep -- Cloudflare's frame inside the
        # Solix app's frame inside assurancewireless.com -- and a challenge
        # that cannot reach storage in its own frame cannot complete. Under
        # storage partitioning it gets a partitioned bucket rather than none,
        # which is usually fine; with third-party cookies actually blocked it
        # gets nothing, and fails with a `600***` code that this form reports
        # as its own "(600)".
        #
        # Opt-in rather than default, because it is a real change to how the
        # browser behaves and the storage check in aw_bot/environment.py will
        # say whether this profile needs it. Turn it on when that check warns.
        extra += [
            "--disable-features=ThirdPartyStoragePartitioning",
            "--disable-third-party-cookie-blocking",
        ]
        LOG.info(
            "[w%d] Third-party storage left open for the nested Turnstile frame",
            worker_id,
        )

    if cfg.headless:
        # Orbita is Chromium: the standard flags apply.
        extra += ["--headless=new", f"--window-size={cfg.window_size}"]

    options = {
        "token": gl_cfg.token,
        "profile_id": profile_id,
        "extra_params": extra,
    }
    if gl_cfg.fresh_session:
        # Start clean: don't pull the account's stored cookies into the profile
        # and don't reopen whatever the last run left on screen.
        options["writeCookiesFromServer"] = False
        options["restore_last_session"] = False

    gl = GoLogin(options)

    if gl_cfg.fresh_session:
        _clear_server_cookies(gl, profile_id, worker_id)

    LOG.info("[w%d] Starting GoLogin profile %s", worker_id, profile_id)
    LOG.info("[w%d] (a new Orbita version downloads on first use -- be patient)", worker_id)
    try:
        debugger_address = gl.start()
    except Exception as exc:
        raise GoLoginError(f"Could not start GoLogin profile {profile_id}: {exc}") from exc

    driver = None
    try:
        driver_path = resolve_chromedriver(gl.get_chromium_version(), gl_cfg.chromedriver_path)
        LOG.info(
            "[w%d] Orbita up on %s (chromedriver: %s)",
            worker_id, debugger_address, driver_path or "resolved by Selenium Manager",
        )
        driver = attach_driver(debugger_address, driver_path, cfg)
        _close_other_tabs(driver, worker_id)
        _size_window_to_screen(driver, cfg, worker_id)
        shim = SBShim(driver, timeout=cfg.page_timeout)
        # Artefact scrubbing only, by default: the profile's own fingerprint
        # is the whole point of running GoLogin. See aw_bot/stealth.py.
        stealth.apply(shim, cfg, "gologin")
        # Independent of the stealth switch: this only watches, and what it
        # watches is the one control that decides whether step 9 goes through.
        turnstile.install(shim, cfg)
        environment.audit(shim, cfg, worker_id)
        yield shim
    except GoLoginError:
        raise
    except Exception as exc:
        if driver is None:
            raise GoLoginError(
                f"Could not attach Selenium to Orbita at {debugger_address}: {exc}"
            ) from exc
        raise
    finally:
        _shutdown(
            driver,
            gl,
            keep_open=cfg.keep_open,
            worker_id=worker_id,
            fresh_session=gl_cfg.fresh_session,
        )


def _close_other_tabs(driver, worker_id: int) -> None:
    """Close the tabs the profile brought with it and keep one.

    Two reasons, and the second one is why this closes them rather than just
    saying they are there, which is all it used to do.

    Speed: every WebDriver command shares the browser with whatever else is
    loaded, and an ad-heavy page left open in another tab slows each one
    measurably -- field entry went from about three seconds to twenty-four
    with a tracker-laden page sitting in the background.

    Measurement: a tab that is not the foreground one has no window geometry
    to report. `window.outerWidth` comes back 0, which is exactly what a
    headless browser reports and what a window on a screen never does -- so
    the session looked headless to anything that checked, and the fingerprint
    audit flagged it. Orbita opens its own start page beside ours, so this was
    happening on every single run.

    The surviving tab is left as the active one, because that is the tab every
    step afterwards works in.
    """
    try:
        handles = driver.window_handles
    except Exception:
        return
    if len(handles) < 2:
        return

    LOG.info("[w%d] Closing %d tab(s) the profile came with", worker_id, len(handles) - 1)

    # Keep whichever tab the driver is already on rather than picking by
    # position: that is the one it attached to, and closing it would leave
    # every later command pointing at a window that no longer exists.
    try:
        keep = driver.current_window_handle
    except Exception:
        keep = handles[-1]
    if keep not in handles:
        keep = handles[-1]
    for handle in handles:
        if handle == keep:
            continue
        try:
            driver.switch_to.window(handle)
            driver.close()
        except Exception as exc:
            LOG.debug("[w%d] Could not close a tab: %s", worker_id, exc)

    try:
        driver.switch_to.window(keep)
    except Exception as exc:
        LOG.warning("[w%d] Could not settle on a single tab: %s", worker_id, exc)


def _size_window_to_screen(driver, cfg: RunConfig, worker_id: int) -> None:
    """Give the window real dimensions, and ones that fit the profile's screen.

    Two failures this prevents.

    A window that has never been sized can report zero outer dimensions --
    the headless signature above. Asking for a size realises the window and
    makes the honest answer a real one.

    And the size has to come from the profile rather than from a constant.
    Each generated fingerprint carries its own screen, so a fixed 1440x1000
    is larger than the screen on any profile that reports, say, 1366x768 --
    a browser window bigger than the monitor it claims to be on, which is a
    sharper contradiction than the one it was meant to fix. So the size is
    taken from `screen.availWidth/availHeight`: the dimensions a maximised
    window actually has on that machine, which is also the most ordinary
    thing for a window to be.
    """
    if cfg.headless:
        # Launched with an explicit --window-size already, and there is no
        # real window to place.
        return

    width = height = 0
    try:
        screen = driver.execute_script(
            "return {w: screen.availWidth, h: screen.availHeight,"
            " fw: screen.width, fh: screen.height};"
        ) or {}
        width = int(screen.get("w") or screen.get("fw") or 0)
        height = int(screen.get("h") or screen.get("fh") or 0)
    except Exception as exc:
        LOG.debug("[w%d] Could not read the profile's screen size: %s", worker_id, exc)

    if width < 800 or height < 600:
        # Unreadable or implausible: fall back to the configured size, which
        # is at least a real window rather than a zero-sized one.
        try:
            width, height = (int(n) for n in cfg.window_size.split(","))
        except Exception:
            width, height = 1440, 1000

    # Clamp to the monitor that actually exists.
    #
    # Everything above came from the browser, and on a GoLogin profile the
    # screen it reports belongs to its fingerprint rather than to this
    # machine. Sizing the window to a fingerprinted 1920x1080 on a smaller
    # physical display puts the bottom of the page below the bottom of the
    # screen -- which the synthetic path never notices, because it addresses
    # the page, and which breaks --real-input completely, because the real
    # mouse can only reach pixels that exist. Measured: the four step 6
    # fields all fell back to synthetic input, the lowest ones first.
    display = real_input.display_size()
    if display:
        margin = 60  # taskbar, and a window not quite filling the screen
        width = min(width, display[0])
        height = min(height, max(600, display[1] - margin))

    try:
        driver.set_window_position(0, 0)
        driver.set_window_size(width, height)
        LOG.info("[w%d] Window sized to %dx%d", worker_id, width, height)
    except Exception as exc:
        LOG.warning(
            "[w%d] Could not size the window (%s). It may report zero outer "
            "dimensions, which reads as headless.", worker_id, exc,
        )


def _clear_server_cookies(gl: GoLogin, profile_id: str, worker_id: int) -> None:
    """Drop the cookies GoLogin holds for this profile.

    Not belt-and-braces: earlier runs (before fresh_session existed, or any run
    that saved) may already have committed a block cookie to the account's copy
    of the profile, and start() would write it straight back into the browser.
    """
    try:
        result = gl.clearCookies(profile_id) or {}
    except Exception as exc:
        LOG.warning("[w%d] Could not clear stored cookies: %s", worker_id, exc)
        return
    if result.get("status") != "success":
        LOG.warning("[w%d] GoLogin would not clear the stored cookies: %s", worker_id, result)


def _stop_without_saving(gl: GoLogin, worker_id: int) -> None:
    """Stop the browser and discard what it did, instead of saving it back.

    GoLogin's stop() ends with commitProfile(), which uploads the browser's
    state to the account. Setting `local` is the switch stop() itself checks to
    skip that -- it also skips the temp-file cleanup that follows, so we do
    that part here.
    """
    profile_path = getattr(gl, "profile_path", None)
    zip_path = getattr(gl, "profile_zip_path_upload", None)

    gl.local = True
    try:
        gl.stop()
    finally:
        for path in (zip_path,):
            try:
                if path and os.path.exists(path):
                    os.remove(path)
            except OSError as exc:
                LOG.debug("Could not remove %s: %s", path, exc)
        try:
            if profile_path and os.path.isdir(profile_path):
                shutil.rmtree(profile_path, ignore_errors=True)
        except OSError as exc:
            LOG.debug("Could not remove %s: %s", profile_path, exc)


def _shutdown(
    driver, gl: GoLogin, keep_open: bool, worker_id: int, fresh_session: bool = True
) -> None:
    if keep_open:
        if driver is not None:
            # Stop chromedriver but not Orbita: driver.quit() would close the
            # browser out from under the profile.
            try:
                driver.service.stop()
            except Exception:
                pass
        LOG.info(
            "[w%d] Browser left running. Close it from the GoLogin app so the "
            "profile (cookies, session) is saved back to your account.",
            worker_id,
        )
        return

    if driver is not None:
        # close(), not quit(): gl.stop() is what shuts Orbita down and syncs the
        # profile back, and quit() would pull the browser out from under it.
        try:
            driver.close()
        except Exception:
            pass

    try:
        if fresh_session:
            LOG.info("[w%d] Stopping profile and discarding this run's session", worker_id)
            _stop_without_saving(gl, worker_id)
        else:
            LOG.info("[w%d] Stopping profile and syncing it back to GoLogin", worker_id)
            gl.stop()
    except Exception as exc:
        LOG.warning("[w%d] GoLogin stop() failed: %s", worker_id, exc)
